version: "2"
services:
  frontend:
    image: frontend:latest
    container_name: frontend
    build: .

    ports:
      - 3000:3000

    networks:
      - cts-dashboard

networks:
  cts-dashboard:
    external: true
